### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by nileshlg2003** [kudan-eu/Simple-Samples#1]
Is there any Android sample with documentation?
I have downloaded the SDk for android and tried to build and run the sample project but it work work. gives Application not responding. Log doesn't reveal much either. :(
 Is there (will there be) any cloud support like vuforia?

**Comment by eddy-kudan** [comment]
The Android SDK download from our site contains the Android sample code, the Github repo for this will also be available soon. There will also be an update to the Android SDK to address some of the bugs users have found.
We are just in the process of finalising the documentation to go along with the Android SDK.

As for cloud support, the framework is compatible with third-party CMSs and allows easy integration with existing apps.
