### ISSUE TITLE
AR 3d model do not work

### ISSUE THREAD

**Issue by rightwaitforyou** [kudan-eu/Simple-Samples#2]
I use that AR toolKit export the armodel  (the source model is 3dmax FBX)  ,but not work ,the error  
     
       Kudan Simple Samples(2575,0x100d70000) malloc: *** mach_vm_map(size=536870912) failed (error code=3)
*** error: can't allocate region

*** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc
(lldb)

**Comment by zhuyuping** [comment]
the kudan AR toolkit  app  just  mac version ,   Is there any Windows version ,Linux version?

**Comment by zhuyuping** [comment]
kudan AR toolkit app have some bugs , convert 3D model  and convert mp4 video is not work

**Comment by eddy-kudan** [comment]
Can you please get in touch with us via the feedback@kudan.eu address and send along your FBX model so that we can research as to why it's having problems being converted.

As in regards to the Kudan AR Toolkit, it is currently OS X only.
